import { render, screen } from '@nba-app/test-utils';
import { TodayGame } from '../TodayGame';

describe('TodayGame', () => {
  it('should render grey background in dark mode', () => {
    render(
      <TodayGame
        game={{
          profile: {
            arenaLocation: 'Boston, MA',
            arenaName: 'TD Garden',
            awayTeamId: '1610612746',
            dateTimeEt: '2022-12-29T19:30',
            gameId: '0022200525',
            homeTeamId: '1610612738',
            number: '525',
            scheduleCode: null,
            seasonType: '2',
            sequence: '3',
            utcMillis: '1672360200000',
          },
          boxscore: {
            attendance: '0',
            awayScore: 110,
            gameLength: '132',
            homeScore: 116,
            leadChanges: 11,
            officialsDisplayName1: 'Scott Foster',
            officialsDisplayName2: 'Brent Barnaky',
            officialsDisplayName3: 'Matt Myers',
            period: '4',
            periodClock: '',
            status: '3',
            statusDesc: 'Final',
            ties: '6',
          },
          urls: [],
          broadcasters: [],
          homeTeam: {
            profile: {
              abbr: 'BOS',
              city: 'Boston',
              cityEn: 'Boston',
              code: 'celtics',
              conference: 'Eastern',
              displayAbbr: 'BOS',
              displayConference: 'Eastern',
              division: 'Atlantic',
              id: '1610612738',
              isAllStarTeam: false,
              isLeagueTeam: true,
              leagueId: '00',
              name: 'Celtics',
              nameEn: 'Celtics',
            },
            matchup: {
              confRank: '1',
              divRank: '1',
              losses: '10',
              seriesText: null,
              wins: '26',
            },
            score: {
              assists: 22,
              biggestLead: 13,
              blocks: 7,
              blocksAgainst: 4,
              defRebs: 38,
              disqualifications: 0,
              ejections: 0,
              fastBreakPoints: 17,
              fga: 91,
              fgm: 44,
              fgpct: 48.4,
              flagrantFouls: 0,
              fouls: 17,
              fta: 22,
              ftm: 17,
              ftpct: 77.3,
              fullTimeoutsRemaining: 2,
              mins: 240,
              offRebs: 11,
              ot10Score: 0,
              ot1Score: 0,
              ot2Score: 0,
              ot3Score: 0,
              ot4Score: 0,
              ot5Score: 0,
              ot6Score: 0,
              ot7Score: 0,
              ot8Score: 0,
              ot9Score: 0,
              pointsInPaint: 54,
              pointsOffTurnovers: 12,
              q1Score: 27,
              q2Score: 33,
              q3Score: 24,
              q4Score: 32,
              rebs: 49,
              score: 116,
              seconds: 0,
              shortTimeoutsRemaining: 0,
              steals: 3,
              technicalFouls: 0,
              tpa: 39,
              tpm: 11,
              tppct: 28.2,
              turnovers: 12,
            },
            pointGameLeader: {
              profile: {
                code: 'jayson_tatum',
                country: 'United States',
                countryEn: 'United States',
                displayAffiliation: 'Duke/United States',
                displayName: 'Jayson Tatum',
                displayNameEn: 'Jayson Tatum',
                dob: '888901200000',
                draftYear: '2017',
                experience: '5',
                firstInitial: 'J',
                firstName: 'Jayson',
                firstNameEn: 'Jayson',
                height: '2.03',
                jerseyNo: '0',
                lastName: 'Tatum',
                lastNameEn: 'Tatum',
                leagueId: '00',
                playerId: '1628369',
                position: 'F-G',
                schoolType: 'College',
                weight: '95.3 kg',
              },
              statTotal: {
                assists: 1,
                blocks: 1,
                defRebs: 10,
                efficiency: 15,
                fga: 26,
                fgm: 10,
                fgpct: 38.5,
                fouls: 2,
                fta: 10,
                ftm: 6,
                ftpct: 60,
                mins: 35,
                offRebs: 1,
                points: 29,
                rebs: 11,
                secs: 45,
                steals: 0,
                technicalFouls: 0,
                tpa: 11,
                tpm: 3,
                tppct: 27.3,
                turnovers: 2,
              },
            },
            assistGameLeader: {
              profile: {
                code: 'marcus_smart',
                country: 'United States',
                countryEn: 'United States',
                displayAffiliation: 'Oklahoma State/United States',
                displayName: 'Marcus Smart',
                displayNameEn: 'Marcus Smart',
                dob: '762930000000',
                draftYear: '2014',
                experience: '8',
                firstInitial: 'M',
                firstName: 'Marcus',
                firstNameEn: 'Marcus',
                height: '1.93',
                jerseyNo: '36',
                lastName: 'Smart',
                lastNameEn: 'Smart',
                leagueId: '00',
                playerId: '203935',
                position: 'G',
                schoolType: 'College',
                weight: '99.8 kg',
              },
              statTotal: {
                assists: 9,
                blocks: 1,
                defRebs: 3,
                efficiency: 15,
                fga: 15,
                fgm: 7,
                fgpct: 46.7,
                fouls: 2,
                fta: 2,
                ftm: 1,
                ftpct: 50,
                mins: 37,
                offRebs: 0,
                points: 17,
                rebs: 3,
                secs: 10,
                steals: 2,
                technicalFouls: 0,
                tpa: 7,
                tpm: 2,
                tppct: 28.6,
                turnovers: 3,
              },
            },
            reboundGameLeader: {
              profile: {
                code: 'jayson_tatum',
                country: 'United States',
                countryEn: 'United States',
                displayAffiliation: 'Duke/United States',
                displayName: 'Jayson Tatum',
                displayNameEn: 'Jayson Tatum',
                dob: '888901200000',
                draftYear: '2017',
                experience: '5',
                firstInitial: 'J',
                firstName: 'Jayson',
                firstNameEn: 'Jayson',
                height: '2.03',
                jerseyNo: '0',
                lastName: 'Tatum',
                lastNameEn: 'Tatum',
                leagueId: '00',
                playerId: '1628369',
                position: 'F-G',
                schoolType: 'College',
                weight: '95.3 kg',
              },
              statTotal: {
                assists: 1,
                blocks: 1,
                defRebs: 10,
                efficiency: 15,
                fga: 26,
                fgm: 10,
                fgpct: 38.5,
                fouls: 2,
                fta: 10,
                ftm: 6,
                ftpct: 60,
                mins: 35,
                offRebs: 1,
                points: 29,
                rebs: 11,
                secs: 45,
                steals: 0,
                technicalFouls: 0,
                tpa: 11,
                tpm: 3,
                tppct: 27.3,
                turnovers: 2,
              },
            },
          },
          awayTeam: {
            profile: {
              abbr: 'LAC',
              city: 'LA',
              cityEn: 'LA',
              code: 'clippers',
              conference: 'Western',
              displayAbbr: 'LAC',
              displayConference: 'Western',
              division: 'Pacific',
              id: '1610612746',
              isAllStarTeam: false,
              isLeagueTeam: true,
              leagueId: '00',
              name: 'Clippers',
              nameEn: 'Clippers',
            },
            matchup: {
              confRank: '4',
              divRank: '1',
              losses: '16',
              seriesText: null,
              wins: '21',
            },
            score: {
              assists: 26,
              biggestLead: 4,
              blocks: 4,
              blocksAgainst: 7,
              defRebs: 33,
              disqualifications: 0,
              ejections: 0,
              fastBreakPoints: 11,
              fga: 89,
              fgm: 43,
              fgpct: 48.3,
              flagrantFouls: 0,
              fouls: 20,
              fta: 14,
              ftm: 9,
              ftpct: 64.3,
              fullTimeoutsRemaining: 0,
              mins: 240,
              offRebs: 8,
              ot10Score: 0,
              ot1Score: 0,
              ot2Score: 0,
              ot3Score: 0,
              ot4Score: 0,
              ot5Score: 0,
              ot6Score: 0,
              ot7Score: 0,
              ot8Score: 0,
              ot9Score: 0,
              pointsInPaint: 42,
              pointsOffTurnovers: 18,
              q1Score: 26,
              q2Score: 23,
              q3Score: 36,
              q4Score: 25,
              rebs: 41,
              score: 110,
              seconds: 0,
              shortTimeoutsRemaining: 0,
              steals: 4,
              technicalFouls: 1,
              tpa: 39,
              tpm: 15,
              tppct: 38.5,
              turnovers: 13,
            },
            pointGameLeader: {
              profile: {
                code: 'kawhi_leonard',
                country: 'United States',
                countryEn: 'United States',
                displayAffiliation: 'San Diego State/United States',
                displayName: 'Kawhi Leonard',
                displayNameEn: 'Kawhi Leonard',
                dob: '678168000000',
                draftYear: '2011',
                experience: '10',
                firstInitial: 'K',
                firstName: 'Kawhi',
                firstNameEn: 'Kawhi',
                height: '2.01',
                jerseyNo: '2',
                lastName: 'Leonard',
                lastNameEn: 'Leonard',
                leagueId: '00',
                playerId: '202695',
                position: 'F',
                schoolType: 'College',
                weight: '102.1 kg',
              },
              statTotal: {
                assists: 3,
                blocks: 1,
                defRebs: 8,
                efficiency: 19,
                fga: 16,
                fgm: 11,
                fgpct: 68.8,
                fouls: 4,
                fta: 1,
                ftm: 1,
                ftpct: 100,
                mins: 36,
                offRebs: 0,
                points: 26,
                rebs: 8,
                secs: 52,
                steals: 0,
                technicalFouls: 0,
                tpa: 6,
                tpm: 3,
                tppct: 50,
                turnovers: 3,
              },
            },
            assistGameLeader: {
              profile: {
                code: 'paul_george',
                country: 'United States',
                countryEn: 'United States',
                displayAffiliation: 'Fresno State/United States',
                displayName: 'Paul George',
                displayNameEn: 'Paul George',
                dob: '641620800000',
                draftYear: '2010',
                experience: '12',
                firstInitial: 'P',
                firstName: 'Paul',
                firstNameEn: 'Paul',
                height: '2.03',
                jerseyNo: '13',
                lastName: 'George',
                lastNameEn: 'George',
                leagueId: '00',
                playerId: '202331',
                position: 'F',
                schoolType: 'College',
                weight: '99.8 kg',
              },
              statTotal: {
                assists: 6,
                blocks: 0,
                defRebs: 4,
                efficiency: 14,
                fga: 22,
                fgm: 10,
                fgpct: 45.5,
                fouls: 4,
                fta: 1,
                ftm: 1,
                ftpct: 100,
                mins: 40,
                offRebs: 0,
                points: 24,
                rebs: 4,
                secs: 18,
                steals: 2,
                technicalFouls: 0,
                tpa: 9,
                tpm: 3,
                tppct: 33.3,
                turnovers: 4,
              },
            },
            reboundGameLeader: {
              profile: {
                code: 'ivica_zubac',
                country: 'Croatia',
                countryEn: 'Croatia',
                displayAffiliation: 'Mega Basket/Croatia',
                displayName: 'Ivica Zubac',
                displayNameEn: 'Ivica Zubac',
                dob: '858661200000',
                draftYear: '2016',
                experience: '6',
                firstInitial: 'I',
                firstName: 'Ivica',
                firstNameEn: 'Ivica',
                height: '2.13',
                jerseyNo: '40',
                lastName: 'Zubac',
                lastNameEn: 'Zubac',
                leagueId: '00',
                playerId: '1627826',
                position: 'C',
                schoolType: 'International',
                weight: '108.9 kg',
              },
              statTotal: {
                assists: 0,
                blocks: 1,
                defRebs: 7,
                efficiency: 12,
                fga: 9,
                fgm: 6,
                fgpct: 66.7,
                fouls: 3,
                fta: 4,
                ftm: 1,
                ftpct: 25,
                mins: 29,
                offRebs: 4,
                points: 13,
                rebs: 11,
                secs: 57,
                steals: 1,
                technicalFouls: 0,
                tpa: 0,
                tpm: 0,
                tppct: 0,
                turnovers: 1,
              },
            },
          },
          ifNecessary: false,
          seriesText: null,
        }}
      />,
      {
        mode: 'dark',
      }
    );

    expect(screen.getByLabelText(/clippers @ celtics/i)).toHaveStyle(
      'background-color: #212121'
    );
  });
});
