name: Integration CI

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  setup:
    name: Setup dependencies
    uses: ./.github/workflows/reusable-setup.yml
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Run lint
        run: pnpm nx run-many --target=lint
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Run unit test
        run: pnpm nx run-many --target=test
